### ISSUE TITLE
getting an error like this for the asos data

### ISSUE THREAD

**Issue by jeevanu** [QData/spacetimeformer#21] opened 2021-12-30 05:51 UTC
File "c:\users\jeeva\downloads\spacetimeformer\spacetimeformer\forecaster.py", line 164, in _log_stats
    self.log(f"{section}/{key}", outs[key].mean(), sync_dist=True)
AttributeError: 'float' object has no attribute 'mean'

**Comment by jakegrigsby** [comment] 2022-01-20 00:31
I think this was an issue caused by the older version of pytorch lightning logging with array stats from each gpu while the new version seems to handle that for us. Should be fixed now

**Closed by jakegrigsby** 2022-01-20 00:31 UTC
