### ISSUE TITLE
"CUDA extension for cauchy multiplication not found" when running toy project

### ISSUE THREAD

**Issue by christofer-f** [QData/spacetimeformer#45] opened 2022-05-18 20:50 UTC
Hi!

I get error "cauchy multiplication not found" when running the command below.
I have tried the suggested "python setup install" in the cachy directory without success.

```
python train.py spacetimeformer toy2 --run_name spatiotemporal_toy2 --d_model 100 --d_ff 400 --enc_layers 2 --dec_layers 2 --gpus 0 --batch_size 32 --start_token_len 4 --n_heads 4 --grad_clip_norm 1 --early_stopping --trials 1

CUDA extension for cauchy multiplication not found. go to ./extensions/cauchy and try `python setup.py install`
```

Any tips how to fix this error?

**Comment by jakegrigsby** [comment] 2022-05-19 12:43
Hi, this is caused by trying to import the S4 model's custom cuda kernels. I forgot there was a manual process to that install. I'm about to make a large update to the repo for the second version of the paper and this should be fixed.

**Comment by CaitlynChavez** [comment] 2022-06-02 07:44
Hi @jakegrigsby, thanks for a clean code release. I am having the same issue. When do you plan on pushing the updated code? Thanks!

```
$ python train.py spacetimeformer solar_energy
CUDA extension for cauchy multiplication not found. go to ./extensions/cauchy and try `python setup.py install`
```

**Comment by jakegrigsby** [comment] 2022-07-02 02:37
Sorry for the long delay on this everyone. My version of the code got too far ahead of the public release and I had to stop trying to maintain this for a few weeks. I just merged a large update which should make this import optional as long as you aren't using the s4 model.

**Closed** 2022-10-07 02:28 UTC
